### ISSUE TITLE
xOnlyFadi sources not working due to cloudflare error

### ISSUE THREAD

**Issue by chailjc** [TheNetsky/extensions-generic-0.8#105]
**Describe the bug**
xOnlyFadi sources will always show error message when opening the app. Bookmarked comics still appear in library but no pages will load.

**To Reproduce**
1. Open Paperback.
2. Click on any xOnlyFadi sources.
3. See error

**Expected behavior**
For error message to stop appearing and for comic to load.

**Screenshots/Video**
![image](https://github.com/user-attachments/assets/548b90ba-735d-4566-8b0e-2bb62d16de43)

**App version**
- v0.8.8 (24)

**Source WITH source version**
- ReadComicOnline 2.0.3

**Additional context**
Webpage still loads and comics can be opened in cloudflare, but not from the app.

**Comment by TheNetsky** [comment]
Wrong repo
