### ISSUE TITLE
[BUG] Mangastream AsuraScans 

### ISSUE THREAD

**Issue by Rodolfosjs** [TheNetsky/extensions-generic-0.8#108]
It isn’t loading in paperback

**Comment by Rodolfosjs** [comment]
I don’t know if it would solve the problem, but the extension could be from asura-scans.com instead of asuracomic.net

**Comment by MaosyBaos** [comment]
AsuraScans source by Netsky won’t work anymore. Someone in the server is creating a new one for their new site

**Comment by TheNetsky** [comment]
What he said, will be removed later
