### ISSUE TITLE
[BUG]  asurascans some manhwas not loading

### ISSUE THREAD

**Issue by Sahibs1** [TheNetsky/extensions-generic-0.8#125]
On asurascans v4.3.1 some manhwa do not load. The error on the picture is the one that shows up. It was for regressor of the fallen family, the executioner and more. The paperback version is v0.8.8-r31. 
![IMG_2030](https://github.com/user-attachments/assets/8847a5bb-2af9-4863-a064-6462378ba244)
![IMG_2031](https://github.com/user-attachments/assets/4182aabe-941e-401d-9515-02d8c234cd2d)

**Comment by TheNetsky** [comment]
Make a backup and reinstall the app, also make sure to migrate if you haven't already
