### ISSUE TITLE
[BUG] Broken Mangakakalot source

### ISSUE THREAD

**Issue by OkilSaber** [TheNetsky/extensions-generic-0.8#131]
**Describe the bug**
The Front page of the Mangakakalot source is broken. Some entries appear in duplicate in the « NewTitles » section. The entries in this section have no chapter and when trying to open one a JS error appears.
When clicking share on some entries it actually gives manganato link. 
I tried removing and adding back the extension. reloading it but it still does not work.

![IMG_7918](https://github.com/user-attachments/assets/f3833e9e-e0fb-4379-85cc-28c198037dbb)
![IMG_7920](https://github.com/user-attachments/assets/bfebc5fa-abc2-492a-9622-39bbbb9f92bd)
![IMG_7921](https://github.com/user-attachments/assets/02a63c25-05d6-444c-b73c-76745d938951)

**Comment by TheNetsky** [comment]
Not an error, check website itself, it has duplicate manga with no chapters, so the error is valid and so are the duplicate manga.

**Comment by OkilSaber** [comment]
Thank you for your feedback. What about the chapmanganato link when sharing? Is it an actual error or the website's fault?

**Comment by TheNetsky** [comment]
Yes, please the the website itself.
