### ISSUE TITLE
Some sources are not working

### ISSUE THREAD

**Issue by AileenSeditio** [TheNetsky/extensions-generic-0.8#18]
**Describe the bug**
Some sources like Zinmanga is not showing the mangas (no error showed) and Kissmanga is getting cloudflare bypass error

**To Reproduce**
1. Go to settings
2. Click on Extensions
3. Enable Zinmanga and Kissmanga sources
4. Go to Discover
5. Click on KissManga tab
6. See Error
7. Click on Zinmanga
8. See Error

**Expected behavior**

**Screenshots/Video**
This is the Kissmanga screenshot

![photo_2023-05-15_10-48-00](https://github.com/TheNetsky/extensions-generic-0.8/assets/122348544/46e1460d-e056-40f0-9fab-3ed60882681b)

This is the ZinManga screenshot
![photo_2023-05-15_10-48-00](https://github.com/TheNetsky/extensions-generic-0.8/assets/122348544/f2384622-d08c-43b6-b1cf-93f0962f2804)

**App version**
- v0.8-r56

**Source WITH source version**
- version : 3.0.3

**Additional context**

**Comment by TheNetsky** [comment]
Fixed, for ZinManga you'll likely have to migrate from ZinManga to ZinManga.
