### ISSUE TITLE
MangaHub Error

### ISSUE THREAD

**Issue by hishamshp** [TheNetsky/extensions-generic-0.8#20]
Mangahub not working, error shown:
@ Paperback: JSError Error
[PaperbackError (300)] JSError Error:
API LIMIT EXCEEDED!
Try doing to CloudFlare again bypass or come back later! - @: 1664:28

When doing CF bypass, the browser automatically redirects to a single manga title, opening chapter from there automatically jumps backs to the same title

**Comment by TheNetsky** [comment]
Fixed in 3.0.8

**Comment by TheNetsky** [comment]
Also wrong repo.
