### ISSUE TITLE
[BUG] Lily Manga doesn’t work anymore v6

### ISSUE THREAD

**Issue by StayPure** [TheNetsky/extensions-generic-0.8#23]
[INFO] [2023-06-15T05:18:51.426Z] [JavaScriptModel:init(for:mainFileLocation:):58] Injected Logger
[INFO] [2023-06-15T05:18:51.620Z] [SourceModel:injectTypes():39] Registered 34 Types
[INFO] [2023-06-15T05:18:51.622Z] [JavaScriptModel:init(for:mainFileLocation:):60] Injected Types
[INFO] [2023-06-15T05:18:51.627Z] [JavaScriptModel:injectTypeWrappers():111] Registered 43 Type Wrappers
[INFO] [2023-06-15T05:18:51.629Z] [JavaScriptModel:init(for:mainFileLocation:):62] Injected Type Wrappers
[INFO] [2023-06-15T05:18:51.629Z] [JavaScriptModel:init(for:mainFileLocation:):64] Injected App Constants
[INFO] [2023-06-15T05:18:51.861Z] [AsyncJS:initialiseSource(from:):103] Injected Cheerio.js - 0.22.0
[INFO] [2023-06-15T05:18:51.876Z] [JavaScriptModel:initialiseExtension():124] Injected Cheerio.js - 0.22.0
[INFO] [2023-06-15T05:18:51.977Z] [JavaScriptModel:initialiseExtension():128] Injected source.LilyManga.js
[INFO] [2023-06-15T05:18:51.981Z] [JavaScriptModel:init(for:mainFileLocation:):66] Initialised Extension: LilyManga - 2.2.6 by Netsky
[INFO] [2023-06-15T05:18:51.983Z] [AsyncJS:initialiseSource(from:):107] Injected source.LilyManga.js
[INFO] [2023-06-15T06:03:34.276Z] [JavaScriptModel:init(for:mainFileLocation:):58] Injected Logger
[INFO] [2023-06-15T06:03:34.506Z] [SourceModel:injectTypes():39] Registered 34 Types
[INFO] [2023-06-15T06:03:34.508Z] [JavaScriptModel:init(for:mainFileLocation:):60] Injected Types
[INFO] [2023-06-15T06:03:34.512Z] [JavaScriptModel:injectTypeWrappers():111] Registered 43 Type Wrappers
[INFO] [2023-06-15T06:03:34.521Z] [JavaScriptModel:init(for:mainFileLocation:):62] Injected Type Wrappers
[INFO] [2023-06-15T06:03:34.532Z] [JavaScriptModel:init(for:mainFileLocation:):64] Injected App Constants
[INFO] [2023-06-15T06:03:34.739Z] [AsyncJS:initialiseSource(from:):103] Injected Cheerio.js - 0.22.0
[INFO] [2023-06-15T06:03:34.745Z] [JavaScriptModel:initialiseExtension():124] Injected Cheerio.js - 0.22.0
[INFO] [2023-06-15T06:03:34.838Z] [AsyncJS:initialiseSource(from:):107] Injected source.LilyManga.js
[INFO] [2023-06-15T06:03:34.861Z] [JavaScriptModel:initialiseExtension():128] Injected source.LilyManga.js
[INFO] [2023-06-15T06:03:34.864Z] [JavaScriptModel:init(for:mainFileLocation:):66] Initialised Extension: LilyManga - 2.2.6 by Netsky
[INFO] [2023-06-15T06:05:20.654Z] [JavaScriptModel:init(for:mainFileLocation:):58] Injected Logger
[INFO] [2023-06-15T06:05:20.683Z] [SourceModel:injectTypes():39] Registered 34 Types
[INFO] [2023-06-15T06:05:20.686Z] [JavaScriptModel:init(for:mainFileLocation:):60] Injected Types
[INFO] [2023-06-15T06:05:20.691Z] [JavaScriptModel:injectTypeWrappers():111] Registered 43 Type Wrappers
[INFO] [2023-06-15T06:05:20.692Z] [JavaScriptModel:init(for:mainFileLocation:):62] Injected Type Wrappers
[INFO] [2023-06-15T06:05:20.693Z] [JavaScriptModel:init(for:mainFileLocation:):64] Injected App Constants
[INFO] [2023-06-15T06:05:20.745Z] [AsyncJS:initialiseSource(from:):103] Injected Cheerio.js - 0.22.0
[INFO] [2023-06-15T06:05:20.748Z] [JavaScriptModel:initialiseExtension():124] Injected Cheerio.js - 0.22.0
[INFO] [2023-06-15T06:05:20.773Z] [AsyncJS:initialiseSource(from:):107] Injected source.LilyManga.js
[INFO] [2023-06-15T06:05:20.775Z] [JavaScriptModel:initialiseExtension():128] Injected source.LilyManga.js
[INFO] [2023-06-15T06:05:20.776Z] [JavaScriptModel:init(for:mainFileLocation:):66] Initialised Extension: LilyManga - 2.2.6 by Netsky
[INFO] [2023-06-15T06:05:41.409Z] [JavaScriptModel:init(for:mainFileLocation:):58] Injected Logger
[INFO] [2023-06-15T06:05:41.418Z] [SourceModel:injectTypes():39] Registered 34 Types
[INFO] [2023-06-15T06:05:41.420Z] [JavaScriptModel:init(for:mainFileLocation:):60] Injected Types
[INFO] [2023-06-15T06:05:41.423Z] [JavaScriptModel:injectTypeWrappers():111] Registered 43 Type Wrappers
[INFO] [2023-06-15T06:05:41.424Z] [JavaScriptModel:init(for:mainFileLocation:):62] Injected Type Wrappers
[INFO] [2023-06-15T06:05:41.426Z] [JavaScriptModel:init(for:mainFileLocation:):64] Injected App Constants
[INFO] [2023-06-15T06:05:41.462Z] [AsyncJS:initialiseSource(from:):103] Injected Cheerio.js - 0.22.0
[INFO] [2023-06-15T06:05:41.465Z] [JavaScriptModel:initialiseExtension():124] Injected Cheerio.js - 0.22.0
[INFO] [2023-06-15T06:05:41.473Z] [AsyncJS:initialiseSource(from:):107] Injected source.LilyManga.js
[ERROR] [2023-06-15T06:05:41.475Z] [AsyncJS:configureConsoleLog():59] [JAVASCRIPT EXCEPTION] ReferenceError: Can't find variable: App MESSAGE: Can't find variable: App Method: Madara@
[ERROR] [2023-06-15T06:05:41.476Z] [AsyncJS:configureConsoleLog():59] LilyManga@:1484:34 
[INFO] [2023-06-15T06:05:41.477Z] [JavaScriptModel:initialiseExtension():128] Injected source.LilyManga.js
[ERROR] [2023-06-15T06:05:41.478Z] [JavaScriptModel:injectLogger():81] [JAVASCRIPT EXCEPTION] Optional(ReferenceError: Can't find variable: App) Method: Madara@
[ERROR] [2023-06-15T06:05:41.478Z] [JavaScriptModel:injectLogger():81] LilyManga@:1484:34 
[INFO] [2023-06-15T06:05:41.479Z] [JavaScriptModel:init(for:mainFileLocation:):66] Initialised Extension: LilyManga - 3.0.5 by Netsky
[ERROR] [2023-06-15T06:05:48.393Z] [JavaScriptModel:injectLogger():81] [JAVASCRIPT EXCEPTION] Optional(TypeError: undefined is not an object) Method: undefined:undefined:undefined 
[ERROR] [2023-06-15T06:05:48.395Z] [JavaScriptModel:injectLogger():81] [JAVASCRIPT EXCEPTION] Optional(TypeError: undefined is not an object) Method: undefined:undefined:undefined 
[ERROR] [2023-06-15T06:05:48.396Z] [SourceModelImplementation:requestManager:18] Invalid type for key requestManager; expected `RequestManager` got `Optional<JSValue>` [PaperbackError(305)] Invalid type for key requestManager; expected `RequestManager` got `Optional<JSValue>`
[ERROR] [2023-06-15T06:05:48.415Z] [JavaScriptModel:injectLogger():81] [JAVASCRIPT EXCEPTION] Optional(TypeError: undefined is not an object) Method: undefined:undefined:undefined 
[ERROR] [2023-06-15T06:05:48.416Z] [SourceModelImplementation:getChapters(forMangaId:):68] MethodNotImplementedError [PaperbackError(302)] MethodNotImplementedError: Method `getChapters` does not have a JavaScript implementation
[ERROR] [2023-06-15T06:05:53.419Z] [JavaScriptModel:injectLogger():81] [JAVASCRIPT EXCEPTION] Optional(TypeError: undefined is not an object) Method: undefined:undefined:undefined 
[ERROR] [2023-06-15T06:05:53.422Z] [JavaScriptModel:injectLogger():81] [JAVASCRIPT EXCEPTION] Optional(TypeError: undefined is not an object) Method: undefined:undefined:undefined 
[ERROR] [2023-06-15T06:05:53.423Z] [SourceModelImplementation:requestManager:18] Invalid type for key requestManager; expected `RequestManager` got `Optional<JSValue>` [PaperbackError(305)] Invalid type for key requestManager; expected `RequestManager` got `Optional<JSValue>`
[ERROR] [2023-06-15T06:05:53.445Z] [JavaScriptModel:injectLogger():81] [JAVASCRIPT EXCEPTION] Optional(TypeError: undefined is not an object) Method: undefined:undefined:undefined 
[ERROR] [2023-06-15T06:05:53.447Z] [SourceModelImplementation:getChapters(forMangaId:):68] MethodNotImplementedError [PaperbackError(302)] MethodNotImplementedError: Method `getChapters` does not have a JavaScript implementation
[INFO] [2023-06-15T06:06:10.297Z] [JavaScriptModel:init(for:mainFileLocation:):58] Injected Logger
[INFO] [2023-06-15T06:06:10.313Z] [SourceModel:injectTypes():39] Registered 34 Types
[INFO] [2023-06-15T06:06:10.315Z] [JavaScriptModel:init(for:mainFileLocation:):60] Injected Types
[INFO] [2023-06-15T06:06:10.318Z] [JavaScriptModel:injectTypeWrappers():111] Registered 43 Type Wrappers
[INFO] [2023-06-15T06:06:10.319Z] [JavaScriptModel:init(for:mainFileLocation:):62] Injected Type Wrappers
[INFO] [2023-06-15T06:06:10.321Z] [JavaScriptModel:init(for:mainFileLocation:):64] Injected App Constants
[INFO] [2023-06-15T06:06:10.362Z] [AsyncJS:initialiseSource(from:):103] Injected Cheerio.js - 0.22.0
[INFO] [2023-06-15T06:06:10.363Z] [JavaScriptModel:initialiseExtension():124] Injected Cheerio.js - 0.22.0
[INFO] [2023-06-15T06:06:10.382Z] [AsyncJS:initialiseSource(from:):107] Injected source.LilyManga.js
[INFO] [2023-06-15T06:06:10.383Z] [JavaScriptModel:initialiseExtension():128] Injected source.LilyManga.js
[INFO] [2023-06-15T06:06:10.384Z] [JavaScriptModel:init(for:mainFileLocation:):66] Initialised Extension: LilyManga - 2.2.6 by Netsky
[INFO] [2023-06-15T06:11:18.628Z] [JavaScriptModel:init(for:mainFileLocation:):58] Injected Logger
[INFO] [2023-06-15T06:11:18.638Z] [SourceModel:injectTypes():39] Registered 34 Types
[INFO] [2023-06-15T06:11:18.640Z] [JavaScriptModel:init(for:mainFileLocation:):60] Injected Types
[INFO] [2023-06-15T06:11:18.648Z] [JavaScriptModel:injectTypeWrappers():111] Registered 43 Type Wrappers
[INFO] [2023-06-15T06:11:18.650Z] [JavaScriptModel:init(for:mainFileLocation:):62] Injected Type Wrappers
[INFO] [2023-06-15T06:11:18.652Z] [JavaScriptModel:init(for:mainFileLocation:):64] Injected App Constants
[INFO] [2023-06-15T06:11:18.695Z] [AsyncJS:initialiseSource(from:):103] Injected Cheerio.js - 0.22.0
[INFO] [2023-06-15T06:11:18.697Z] [JavaScriptModel:initialiseExtension():124] Injected Cheerio.js - 0.22.0
[INFO] [2023-06-15T06:11:18.724Z] [AsyncJS:initialiseSource(from:):107] Injected source.LilyManga.js
[INFO] [2023-06-15T06:11:18.726Z] [JavaScriptModel:initialiseExtension():128] Injected source.LilyManga.js
[INFO] [2023-06-15T06:11:18.728Z] [JavaScriptModel:init(for:mainFileLocation:):66] Initialised Extension: LilyManga - 2.2.6 by Netsky
[INFO] [2023-06-15T06:13:15.162Z] [JavaScriptModel:init(for:mainFileLocation:):58] Injected Logger
[INFO] [2023-06-15T06:13:15.173Z] [SourceModel:injectTypes():39] Registered 34 Types
[INFO] [2023-06-15T06:13:15.174Z] [JavaScriptModel:init(for:mainFileLocation:):60] Injected Types
[INFO] [2023-06-15T06:13:15.175Z] [JavaScriptModel:injectTypeWrappers():111] Registered 43 Type Wrappers
[INFO] [2023-06-15T06:13:15.176Z] [JavaScriptModel:init(for:mainFileLocation:):62] Injected Type Wrappers
[INFO] [2023-06-15T06:13:15.177Z] [JavaScriptModel:init(for:mainFileLocation:):64] Injected App Constants
[INFO] [2023-06-15T06:13:15.215Z] [JavaScriptModel:initialiseExtension():124] Injected Cheerio.js - 0.22.0
[INFO] [2023-06-15T06:13:15.233Z] [JavaScriptModel:initialiseExtension():128] Injected source.LilyManga.js
[INFO] [2023-06-15T06:13:15.235Z] [JavaScriptModel:init(for:mainFileLocation:):66] Initialised Extension: LilyManga - 2.2.6 by Netsky
[INFO] [2023-06-15T06:13:15.287Z] [AsyncJS:initialiseSource(from:):103] Injected Cheerio.js - 0.22.0
[INFO] [2023-06-15T06:13:15.306Z] [AsyncJS:initialiseSource(from:):107] Injected source.LilyManga.js
[INFO] [2023-06-15T06:16:10.992Z] [JavaScriptModel:init(for:mainFileLocation:):58] Injected Logger
[INFO] [2023-06-15T06:16:11.004Z] [SourceModel:injectTypes():39] Registered 34 Types
[INFO] [2023-06-15T06:16:11.006Z] [JavaScriptModel:init(for:mainFileLocation:):60] Injected Types
[INFO] [2023-06-15T06:16:11.010Z] [JavaScriptModel:injectTypeWrappers():111] Registered 43 Type Wrappers
[INFO] [2023-06-15T06:16:11.011Z] [JavaScriptModel:init(for:mainFileLocation:):62] Injected Type Wrappers
[INFO] [2023-06-15T06:16:11.013Z] [JavaScriptModel:init(for:mainFileLocation:):64] Injected App Constants
[INFO] [2023-06-15T06:16:11.052Z] [JavaScriptModel:initialiseExtension():124] Injected Cheerio.js - 0.22.0
[INFO] [2023-06-15T06:16:11.053Z] [AsyncJS:initialiseSource(from:):103] Injected Cheerio.js - 0.22.0
[INFO] [2023-06-15T06:16:11.072Z] [AsyncJS:initialiseSource(from:):107] Injected source.LilyManga.js
[INFO] [2023-06-15T06:16:11.073Z] [JavaScriptModel:initialiseExtension():128] Injected source.LilyManga.js
[INFO] [2023-06-15T06:16:11.074Z] [JavaScriptModel:init(for:mainFileLocation:):66] Initialised Extension: LilyManga - 2.2.6 by Netsky
[ERROR] [2023-06-15T06:18:19.029Z] [SourceModelImplementation:getMangaDetails(forId:):63] JSError Error [PaperbackError(300)] JSError Error: Unable to fetch numeric postId for this item!
[ERROR] [2023-06-15T06:18:19.031Z] [SourceModelImplementation:getMangaDetails(forId:):63] Check if path is set correctly! - parsePostId@
[ERROR] [2023-06-15T06:18:19.031Z] [SourceModelImplementation:getMangaDetails(forId:):63] @
[ERROR] [2023-06-15T06:18:19.032Z] [SourceModelImplementation:getMangaDetails(forId:):63] asyncFunctionResume@[native code]
[ERROR] [2023-06-15T06:18:19.033Z] [SourceModelImplementation:getMangaDetails(forId:):63] asyncFunctionResume@[native code]
[ERROR] [2023-06-15T06:18:19.033Z] [SourceModelImplementation:getMangaDetails(forId:):63] @[native code]
[ERROR] [2023-06-15T06:18:19.034Z] [SourceModelImplementation:getMangaDetails(forId:):63] promiseReactionJobWithoutPromise@[native code]
[ERROR] [2023-06-15T06:18:19.035Z] [SourceModelImplementation:getMangaDetails(forId:):63] promiseReactionJob@[native code]:20122:28

**Comment by TheNetsky** [comment]
Seems more like you're trying to install a 0.8 source on a non 0.8 or above app. Source works fine on my end.

**Comment by StayPure** [comment]
Oh! My bad, I think I dropped this on the wrong repo, I’m having issues on the v6 extension.

**Comment by TheNetsky** [comment]
> Oh! My bad, I think I dropped this on the wrong repo, I’m having issues on the v6 extension.

No longer supported, feel free to make your changes and propose a PR.
