### ISSUE TITLE
MangaDex JSError Error

### ISSUE THREAD

**Issue by Lunarrexists** [TheNetsky/extensions-generic-0.8#26]
**Describe the bug**
When updating to mangadex (0.8), mangadex does not load

**To Reproduce**
1. Go to mangadex 3.0.2
2. Click on ‘update’
3. Go to Mangadex tab

**Expected behavior**
The manga to show up

**Screenshots/Video**

**App version**
- v0.4-r69

**Source WITH source version**
- MangaDex 3.0.2

**Additional context**
Have tried before to update to 3.0.2 but always errors out, now old version is erroring out too so need to update

**Comment by Thundernerd** [comment]
MangaDex 3.0.2 works fine if you update your app to a recent version, you're on 0.4 while the latest on the appstore is 0.8.

**Comment by TheNetsky** [comment]
Update app.

**Comment by TheNetsky** [comment]
Also wrong repo.
