### ISSUE TITLE
[BUG] Asura Scans Cloudflare Bypass no longer working 

### ISSUE THREAD

**Issue by aldenparker** [TheNetsky/extensions-generic-0.8#27]
**Describe the bug**
Just a few minute ago I was reading from Asura scans and was completely fine, but then the images stopped loading and when I tried to reload Asura by pulling down, it gave me a Cloudflare bypass error. I clicked on the cloud icon to go to the page and that worked fine, but still get error when I come back to app.

**To Reproduce**
Download Asura Scans
Go to page in app
Refresh 

**Expected behavior**
I expected the source to reload fine and allow me to view it again.

**Screenshots/Video**
![IMG_0112](https://github.com/TheNetsky/extensions-generic-0.8/assets/32986873/9ce10de1-1fc8-4a74-b9f3-59bf3284ef79)

**App version**
- v0.8.3-r2

**Source WITH source version**
- AsuraScans v3.0.1

**Additional context**
Maybe has to do with recent source update or change on Asura scans side? I don’t really know

**Comment by TheNetsky** [comment]
Issue on your end, cannot replicate.

**Comment by StateFarmTaxes** [comment]
I have it as well. Its been happening for about 4 hours. 
![yes](https://github.com/TheNetsky/extensions-generic-0.8/assets/123421684/f8e724c4-d43e-4a66-9e4c-e5875cfb1610)

**Comment by TheNetsky** [comment]
The website does not even have Cloudflare on for me, I can just access it. It's likely something on your end on in your region. Regardless of not something that can be fixed.

**Comment by StateFarmTaxes** [comment]
The website doesn't have Cloudfare either for me that's why I was confused.

**Comment by TheNetsky** [comment]
It is what it is, source works fine for me, nothing I can do here. Try again later.

**Comment by smeeeeeee** [comment]
I've been having the same issue as well

**Comment by Ivanmatthew** [comment]
This is a common issue of their website regardless of using the app. You need to flush the app’s internal site cache. To do this you must delete the app with all it’s data (BE SURE TO MAKE A BACK-UP), and then install it again.

After that it should work how it is expected to be.
