### ISSUE TITLE
[BUG] App crashes after clicking “Thumbnail Quality” for mangadex

### ISSUE THREAD

**Issue by gimmeamin** [TheNetsky/extensions-generic-0.8#28]
**Describe the bug**
The app crashes immediately after pressing.

**To reproduce**
-Go to app settings
-Extensions
-Mangadex
-Thumbnail Quality

**Expected Behavior**
For app not to crash

**App version**
v0.8.3-r2

**Source WITH source version**
MangaDex 3.0.2 (Paperback community extensions 0.8)

**Comment by TheNetsky** [comment]
App issue with settings, works after restart of the app. Not much can be done.
