### ISSUE TITLE
[BUG] Mangatx no chapters

### ISSUE THREAD

**Issue by Mihran77** [TheNetsky/extensions-generic-0.8#29]
**Describe the bug**
No chapter show up on any manga from the Mangatx source.

**To Reproduce**
1. Go to any Mangatx homepage or search for a manga in the source.
2. Click on any of them
3. See that an error show up

**Expected behavior**
I expect the list of chapters to show up and click one of them to read.

**Screenshots/Video**
No screenshot because I’m on a phone, but I can paste the error message 

Paperback: JSError Error
[PaperbackError (300)] JSError Error:
Couldn't find any chapters for mangald:
8790! - parseChapterList@:2066:28

The 8790 is the manga Id and is the only thing that differs in the error message from each manga

**App version**
- v0.8.5-r1

**Source WITH source version**
- Mangatx 3.0.5

**Additional context**
The thumbnails still show up when you open Mangatx in the homepage, the name is still there for the manga it even shows what the latest chapter is under the thumbnail

**Comment by TheNetsky** [comment]
Fixed
