### ISSUE TITLE
[BUG] Just a black screen when loading pages

### ISSUE THREAD

**Issue by gimmeamin** [TheNetsky/extensions-generic-0.8#30]
**Describe the bug**
The pages seem to load… But it appears as just black. Some pages loaded normally at first, but some of them also became black pages later.

**To Reproduce**
1. Using AsuraScans
2. Reading chapter 2 of Worthless Regression
3. The forth page until before the last page are all black
4. Tried closing the app/deleting the history and stuff. Didn’t work.

**Expected behavior**
The pages not to be black. I looked at the official website and it’s fine there.

**Screenshot/Video**
![IMG_3617](https://github.com/TheNetsky/extensions-generic-0.8/assets/77600239/ec5eb953-4dd0-4b55-b176-329477dcf1a5)

**App version**
- v0.8.5-r1

**Source WITH source version**
- AsuraScans 3.0.2 (From: Generic MangaStream 0.8)

**Comment by TheNetsky** [comment]
If the rest works fine, I think this is a one-off issue which I personally will not be fixing.

**Comment by Mihran77** [comment]
I am getting the same problem
I got it before but it
And now a error pop up showed up and the chapters wouldn’t load

Paperback: JSError Error
[PaperbackError(300)] JSError Error:
CLOUDFLARE BYPASS ERROR:
Please go to the homepage of <https:// asura.gg> and press the cloud icon. - checkResponseError@
@:1988:32

I did what it said and the chapter loaded but it was a black screen for every page except the first page
