### ISSUE TITLE
[BUG] InfernalVoidScans cloudflare bypass doesn’t work

### ISSUE THREAD

**Issue by Lunariiar** [TheNetsky/extensions-generic-0.8#31]
**Describe the bug**
Trying to bypass cloudflare on InfernalVoidScans doesn’t work.

**To Reproduce**
1. Go to InfernalVoidScans discover page 
2. Click on the cloud icon top right 
3. Click on „Done“ after the website (void-scans.com) opens 
4. try to check the latest updates

**Expected behavior**
Latest updates show up and no error message to bypass cloudflare.

**Screenshots/Video**

**App version**
- v0.8.6 (from TestFlight)

**Source WITH source version**
-from here: https://thenetsky.github.io/extensions-generic-0.8/mangastream InfernalVoidScans 3.0.0
Author:nicknitewolf

**Comment by TheNetsky** [comment]
And the other sections work?

**Comment by Lunariiar** [comment]
It doesn’t work for latest updates and while searching in it, if I select it in the search section… what works are the first few mangas shown in the „top all“, „top monthly“,…. In the discover page

**Comment by TheNetsky** [comment]
Consider it broken.

**Comment by Ivanmatthew** [comment]
Maybe apply the cloudflare fix for asura??

**Comment by Ivanmatthew** [comment]
Maybe should add a PR for more detailed cloudflare issues. A 520 cloudflare means there's a mismatch between your device and the cloudflare servers, probably when you've visited the site on your device, alongside with using it in paperback, though I don't know the exact issue here.

For now, the fix as always is to reinstall paperback and the sources (don't forget to back up), or uninstall source, wait for around a month for the cache to reset and then install it again.
