### ISSUE TITLE
[BUG] Mangakakalot Error No Chapter

### ISSUE THREAD

**Issue by tyramsihu** [TheNetsky/extensions-generic-0.8#33]
No chapter show up on any manga from the Mangakakalot source.

**Comment by TheNetsky** [comment]
More details please or recording

**Comment by tyramsihu** [comment]
![IMG_2508](https://github.com/TheNetsky/extensions-generic-0.8/assets/126182872/ab0c24c1-20e4-46c2-afc1-9cfab9947210)

https://github.com/TheNetsky/extensions-generic-0.8/assets/126182872/0ce746fb-905d-4397-8697-e76a22c32f58

**Comment by tyramsihu** [comment]
manga dissapear and no chapter on bookmarked manga

**Comment by TheNetsky** [comment]
Do you have the source even installed?

**Comment by tyramsihu** [comment]
yes i have, it works fine yesterday, should i try to reinstall the source or the app?

**Comment by TheNetsky** [comment]
Sure, else post this issue on Discord, troubleshooting like this is not very efficient.
