### ISSUE TITLE
[BUG] AsuraScans does not load

### ISSUE THREAD

**Issue by DreenyGitHub** [TheNetsky/extensions-generic-0.8#34]
**Describe the bug**
AsuraScans does not load when going to the tab however clicking the cloud to open the website opens fine.

**To Reproduce**
1. Go to “AsuraScans” tab
2. Does not load

**Expected behavior**
It should load normally and list manhwa and updates.

**Screenshots/Video**

https://cdn.discordapp.com/attachments/301422613077557248/1139968996226121738/RPReplay_Final1691860056.mov

**App version**
- v0.8.6-r2

**Source WITH source version**
- AsuraScans 3.0.2

**Additional context**
Was working fine before but suddenly stopped working, I can use the website perfectly fine.

**Comment by Thundernerd** [comment]
asura.gg seems to redirect to asura.nacm.xzy now

**Comment by TheNetsky** [comment]
Updated n fixed
