### ISSUE TITLE
Cannot add anything - undefined is not an object

### ISSUE THREAD

**Issue by xxtensazenxx** [TheNetsky/extensions-generic-0.8#4]
Anytime I try to install anything I get the following message 

"Name Of Site: [JAVA SCRIPT EXCEPTION] Optional(TypeError: undefined is not an object) Method: undefined undefined :undefined." 

not really sure where to go from here

**Comment by niclimcy** [comment]
Please furnish more information:
1. Which sources are you trying to install
2. Can we get an "Export app logs" from settings after an attempt to install the source

**Comment by xxtensazenxx** [comment]
I tried MangaDex, Kiss Manga and Manga1st so far. 

[Log here](https://controlc.com/7f996ee6)

**Comment by niclimcy** [comment]
If you are on 0.8 beta, please remove the Madara Generic (0.8) repository and reinstall it here: https://thenetsky.github.io/extensions-generic-0.8/madara/

If you are on 0.7 (AKA the AppStore version), you should not be using this repo at all

**Comment by TheNetsky** [comment]
Gonna mark this as complete, next time provide proper details about the issue.
