### ISSUE TITLE
[BUG] RealmScans URL needs to be updated.

### ISSUE THREAD

**Issue by amenokagaseo** [TheNetsky/extensions-generic-0.8#41]
They recently moved from realmscans.xyz to realmscans.to, and while realmsscans.xyz does redirect to the new site it goes through a bunch of brokers that break everything and redirect to the front page.

**Comment by TheNetsky** [comment]
Source is broken regardless of, so updating the URL won't fix it.

**Comment by Ivanmatthew** [comment]
Solved in PR #43

**Comment by Wicser** [comment]
Hiperdex url has changed so its not loading anymore
