### ISSUE TITLE
Hiperdex url has changed so its not loading anymore

### ISSUE THREAD

**Issue by Wicser** [TheNetsky/extensions-generic-0.8#44]
Hiperdex url has changed so its not loading anymore

_Originally posted by @Wicser in https://github.com/TheNetsky/extensions-generic-0.8/issues/41#issuecomment-1684355420_

**Comment by TheNetsky** [comment]
Again???

**Comment by xOnlyFadi** [comment]
> Again???

make a source setting for both urls and users can change them any time

**Comment by TheNetsky** [comment]
Wdym the URL is already changed?

**Comment by xOnlyFadi** [comment]
> Wdym the URL is already changed?

im saying make a source setting for both hiperdex urls when it's changed they can try and change it via settings

**Comment by TheNetsky** [comment]
Am not gonna do that, feel free to do so
But what I'm asking that it should work, since the URL is already changed.

**Comment by HazardQ** [comment]
They reverted back to .com. 😅

**Comment by Ivanmatthew** [comment]
bruh

**Comment by HazardQ** [comment]
They are back at it. .xyz this time. 😅

**Comment by HazardQ** [comment]
Back to .com again. 😅
