### ISSUE TITLE
[BUG] 1stkissmanga closing down

### ISSUE THREAD

**Issue by ABSabellon** [TheNetsky/extensions-generic-0.8#45]
**Describe the bug**
1stkissmanga is closing down and moving to likemanga.io

**To Reproduce**
1. Go to extensions
2. Click on add 1stkissmanga
3. Go to 1stkissmanga tab 
4. See that manga list no longer updates since last week

**Expected behavior**
I checked the website and it is because they are closing 1stkissmanga

**Screenshots/Video**
[https://imgur.com/a/sSr4SkE](url)

**App version**
- v0.8.6r2

**Comment by TheNetsky** [comment]
New site is not supported by any generic, so not much we can do.
