### ISSUE TITLE
[BUG] AsuraScans isn't loading

### ISSUE THREAD

**Issue by Reiahzz** [TheNetsky/extensions-generic-0.8#49]
**Describe the bug**

- Asurascans isnt working, the page is blank and when you refresh you get an error. i believe the link changed from 'https://asura.nacm.xyz' to 'https://asuracomics.com'

**To Reproduce**

- just tapping on the AsuraScans tab, refresh you get "Paperback: JSError Error [PaperbackError(300)] JSError Error: AsyncOperationTimedOutError - undefined:undefined:undefined

**Expected behavior**

- to see manga titles/images load 

**Screenshots/Video**
![IMG_4982](https://github.com/TheNetsky/extensions-generic-0.8/assets/143884913/d3556a99-d7eb-4cf7-a7d0-ce94e695217f)

**App version 
- v0.8.6-r2

**Source WITH source version**
- AsuraScans 3.0.3

**Additional context**
Tried reinstalling the source but it's still blank

**Comment by TheNetsky** [comment]
Fixed
