### ISSUE TITLE
[BUG] Manganato and Mangakakalot broken source

### ISSUE THREAD

**Issue by xDeltaPLays** [TheNetsky/extensions-generic-0.8#51]
**Describe the bug**
Manganato and Mangakakalot don't load images/chapters
**To Reproduce**
Use the source 
**Expected behavior**
Images/Manga to load
**Screenshots/Video**
![image](https://github.com/TheNetsky/extensions-generic-0.8/assets/144053974/f9baa167-737c-4466-817c-df36b83654c4)
![image](https://github.com/TheNetsky/extensions-generic-0.8/assets/144053974/e9e61903-3823-4123-8b27-1393a57e90d4)

**App version**
Paperback 0.8.6

**Source WITH source version**
MangaBox(0.8)
Mangakakalot/Manganato/BatMeow/4.0.3

**Additional context**

**Comment by TheNetsky** [comment]
Reinstall app

**Comment by xDeltaPLays** [comment]
Thank you and sry for my stupidity?
