### ISSUE TITLE
[BUG] Sushi scan source issue

### ISSUE THREAD

**Issue by B1n00** [TheNetsky/extensions-generic-0.8#52]
**Describe the bug**

systematic error while trying to read a manga from sushi scan source indicating : The requested page was not found. 
tryied to uninstall and reinstall PB without success. 

**To Reproduce**
1. Go to 'random manga from sushi scan'
2. Click on 'it’

**Expected behavior**
The manga could be red

**Screenshots/Video**
![image](https://github.com/TheNetsky/extensions-generic-0.8/assets/77860905/fb3bf5f5-d1ff-47da-a3df-83589200f150)

**App version**
- v0.8.6-r2

**Source WITH source version**
- Sushi scan from mangastream

**Comment by Rycola** [comment]
Same problem on 0.8.7-r1
Website changed from /catalogue/2336/ to /catalogue/one-piece/ breaking all links

**Comment by TheNetsky** [comment]
Fixed, people migrate SushiScan manga to SushiScan manga
