### ISSUE TITLE
ManhuaPlus didn't actually stop working

### ISSUE THREAD

**Issue by hyoretsu** [TheNetsky/extensions-generic-0.8#59]
Even though it's almost 1 day apart, what TheNetsky/community-extensions#14 likely complained about was actually because of this:
![image](https://github.com/TheNetsky/extensions-generic-0.8/assets/20804322/14155f75-5159-4876-a0ed-d107b1b6b71d)

Their original website still works and the old extension that was removed still works. They also link to https://manhuaplus.com in their chat and releases channels and also in every new chapter they release. https://manhuaplus.org is just a backup site.

**Comment by TheNetsky** [comment]
Commit reverted.
