### ISSUE TITLE
[BUG] SuryaScans domain change

### ISSUE THREAD

**Issue by alvarojry** [TheNetsky/extensions-generic-0.8#71]
SuryaScans did a domain change which means https://suryareader.com is no longer being update. New domain is https://suryacomics.com. Information is available in https://suryareader.com.

**Comment by Ivanmatthew** [comment]
> SuryaScans did a domain change which means https://suryareader.com is no longer being update. New domain is https://suryacomics.com. Information is available in https://suryareader.com.

Is it common for them to change domains? How often have they done it so far?
I might make a PR for setting the new domain yourself so users won't have to wait for new PR's

**Comment by alvarojry** [comment]
First time since I have been using the extension that they did the domain change, but it also hasn't been long since I started using it so not really sure.
