### ISSUE TITLE
[BUG] ReadJujutsuKaisen and other MangaCatalog Generic Sources Will Not Load Chapters

### ISSUE THREAD

**Issue by J4YS0N-H** [TheNetsky/extensions-generic-0.8#74]
**Describe the bug**
When going into the manga, content does not load and gives error message:

Paperback: JSError Error
[PaperbackError (300)] JSError Error:
Could not parse out ID when getting chapters for postld:jujutsu-kaisen - @:1617:36

**To Reproduce**
1. Go to ex. ReadJujutsuKaisen
2. Click on any of the mangas
3. Content does not load and displays "could not parse id" error 

**Expected behavior**
The content to load. Was working ok a few days ago.

**Screenshots/Video**
![image](https://github.com/TheNetsky/extensions-generic-0.8/assets/152446540/1763db67-7ef5-4c44-a8ca-0c8c7bbf0dfa)

**App version**
- v0.4-r69

**Source WITH source version**
- ReadJujutsuKaisen 1.0.1 (others in MangaCatalog Generic 0.8 also have same issue, could be user end)

**Additional context**
Reinstalled everything and did best to ensure not on my end.

**Comment by TheNetsky** [comment]
Fixed
