### ISSUE TITLE
[BUG] Mangatx not working

### ISSUE THREAD

**Issue by Mihran77** [TheNetsky/extensions-generic-0.8#75]
**Describe the bug**
Whether you open a manga chapter or open its chapter list an error would pop up and the chapter will be a black screen

**To Reproduce**
1. Go to any mangatx manga (I went to both ‘Rise from the Rubble’ and ‘The Eternal Supreme’)
2. The error will show up once the manga has refreshed (the loading circle in the top right is done)
3. Or click on a chapter and see a black screen(I found out from going to it from my recently read)

**Expected behavior**
I expected to read the chapter

**Screenshots/Video**
I have the error message for the manga

 Paperback: JSError Error
[PaperbackError (300)] JSError Error:
The requested page https:// mangatx.com//mangatx.com/ajax/
chapters was not found! - checkResponseError@
@:8752:32

**App version**
- v0.8.6-r2

**Source WITH source version**
- Mangatx v3.1.3

**Additional context**
I checked just in case, but the website still works.

**Comment by TheNetsky** [comment]
Site is down, next time check site first before opening an issue.

**Comment by Mihran77** [comment]
> Site is down, next time check site first before opening an issue.

The actual site works, it only says maintenance when I go from cloudflare
