### ISSUE TITLE
[BUG] Mangacultivator wont work

### ISSUE THREAD

**Issue by NumanY18** [TheNetsky/extensions-generic-0.8#76]
**Describe the bug**
Only its homepage on discover loads
Errors pop up when any manga is clicked, thus cannot read

**To Reproduce**
1. Go to ‘Discover'
2. Click on 'Mangacultivator home'
3. Scroll down to 'any manga and click'

**Expected behavior**
Manga images should pop as usual

**Screenshots/Video**
If applicable, add screenshots to help explain 
![IMG_6420](https://github.com/TheNetsky/extensions-generic-0.8/assets/152892120/db83b3a0-bf5c-47a0-a84c-b4f8980ce9c4)
![IMG_6419](https://github.com/TheNetsky/extensions-generic-0.8/assets/152892120/40a05b0e-0169-443f-8595-47f36c5eb17d)

**App version**
- v0.8.6-r2

**Source WITH source version**
- Madara Generic 0.8

**Additional context**
Used on IOS 17.1.2

**Comment by TheNetsky** [comment]
Source is dead.
