### ISSUE TITLE
Noticeably Slow Update for MangaSee

### ISSUE THREAD

**Issue by Ari-03** [TheNetsky/extensions-generic-0.8#78]
**Describe the bug**
Compare to other paperback sources, MangaSee source takes a noticeable longer time to update, before paperback recent update I could speed up source by re getting MangaSee source, but now the source update is slow.
**To Reproduce**
1. Update with MangaSee sources

**Screenshots/Video**
https://github.com/TheNetsky/extensions-generic-0.8/assets/64171580/8b02d72d-549f-4be4-9bcc-128cdd1da1fc

**App version**
- v0.8.7-r12

**Source WITH source version**
- MangaSee 3.0.0

**Comment by TheNetsky** [comment]
Slow but working I assume.

Nothing we can do about that.
