### ISSUE TITLE
[BUG] Mangaworld wont work

### ISSUE THREAD

**Issue by Beef94** [TheNetsky/extensions-generic-0.8#80]
**Describe the bug**
Only its homepage on discover loads
Errors pop up when any manga is clicked, thus cannot read

**To Reproduce**
1. Go to ‘Discover'
2. Click on 'Mangaworld home'
3. Scroll down to 'any manga and click'

**App version**
- v0.8
- v0.6

Source WITH source version
NmN's Foreign Extensions

Additional context
Used on IOS 17.1.2

**Comment by TheNetsky** [comment]
Wrong repo
