### ISSUE TITLE
[BUG] Can't download chapter from SushiScans

### ISSUE THREAD

**Issue by alfus5** [TheNetsky/extensions-generic-0.8#86]
**Chapter's won't download**
I have the french manga source *SushiScans*. that have a cloudflare protection. When I'm online, after passing the cloudflare, i can read mangas without any problem. But when I try to download chapters from this source, they queu but the download never start. That making that i can't even download a chapter from this source.

**To Reproduce**
1. Add the Sushiscans extension from Mangaread
2. Click on 'SushiScans' from the discover tab
3. Add one manga to the library
5. Download one chapter
6. Go to the download section
7. See the error, the download never start

**Expected behavior**
The download should start

**Screenshots/Video**
![screen](https://github.com/TheNetsky/extensions-generic-0.8/assets/63202698/2794076f-0989-4c74-b2e5-78562fd08003)

**App version**
- v0.8.7-r12

**Source WITH source version**
- btylerh7 3.0.2

**Additional context**
It' maybe a problem with the fact that tis source have a cloudflare protection.

**Comment by TheNetsky** [comment]
Likely because of Cloudflare, not much can be done against that
