### ISSUE TITLE
[BUG] V0.8.7-r12 Source not work on specific device. Toonily & MangaClash

### ISSUE THREAD

**Issue by olivergiangvu** [TheNetsky/extensions-generic-0.8#87]
There some sources which work on both my other device macOS and Ipad pro but not loading on my IpadMini
Tested   Toonily & MangaClash source have the same error as screen shot

Paperback: JSError Error [PaperbackError(300)] JSError Error:
AsyncOperationTimedOutError - undefined:undefined:undefined

![image](https://github.com/TheNetsky/extensions-generic-0.8/assets/106240777/69adb680-e11f-4439-b0f8-5a2da1a147e3)

![CleanShot 2024-04-08 at 16 34 01](https://github.com/TheNetsky/extensions-generic-0.8/assets/106240777/a41a7c56-c018-4822-8d75-db6849efbcb3)

**Comment by TheNetsky** [comment]
Unable to replicate this, try reinstalling.

**Comment by olivergiangvu** [comment]
> Unable to replicate this, try reinstalling.

I try reinstalled but it still the same - now it happened to my macOS too. out of 3 devices only the iPad Pro can load these sources now.
Kind of strange
