### ISSUE TITLE
[BUG] AsuraScans extension not working

### ISSUE THREAD

**Issue by PoloDePoli** [TheNetsky/extensions-generic-0.8#89]
**Describe the bug**
AsuraScans extension has stopped working today (3 May 2024). This is likely due to change in domain name from _asuratoon.com_ to [asuracomic.net](https://asuracomic.net/)

**App version** 
- v0.8.7-r12

**Source WITH source version**
- AsuraScans Netski | 3.0.9 from Generic Mangastream (0.8)

**Comment by TheNetsky** [comment]
Seems to be working fine, both domains get images from their "asuratoon.com" domain. Issue regarding loading are something on their end.

**Comment by beingsuz** [comment]
asura seems to have changed domain again cannot load chapter with the extension 🫠

**Comment by CostcoFanboy** [comment]
But the chapter links are from asuracomic.net, wouldn't that cause issues with detecting the new chapter?

**Comment by CostcoFanboy** [comment]
But the metadata was moved.

**Comment by PoloDePoli** [comment]
I am not convinced this is resolved/closed.

What I have discovered since I made the post is:

- If I am on LTE the extension works (and the website) exactly as expected
- If am on WiFi (whether it's my own, starbucks, friend's home) the extension fails and when I ask to be sent to the website to read directly I get linked to 404 page not found
  - However if I go directly to Asura (or via the app go to the homepage) I can then read the comic from the website directly without problem (even on the wifi)

Checking on the discord I do not appear to be the only one with the problem, however I have no idea why the issue is appearing and I do suspect is more on Asura side than the extension itself. Though confused why - when I access the website - I can read regardless whether I am on WiFi or LTE but I only am unable to read through the app when on WiFi but can read when on LTE

**Comment by jsand5048** [comment]
I’m experiencing the same issue as the above. I’m able to read fine on the site and can also read fine when off of WiFi

**Comment by TheNetsky** [comment]
> I am not convinced this is resolved/closed.
> 
> What I have discovered since I made the post is:
> 
> * If I am on LTE the extension works (and the website) exactly as expected
> * If am on WiFi (whether it's my own, starbucks, friend's home) the extension fails and when I ask to be sent to the website to read directly I get linked to 404 page not found
>   
>   * However if I go directly to Asura (or via the app go to the homepage) I can then read the comic from the website directly without problem (even on the wifi)
> 
> Checking on the discord I do not appear to be the only one with the problem, however I have no idea why the issue is appearing and I do suspect is more on Asura side than the extension itself. Though confused why - when I access the website - I can read regardless whether I am on WiFi or LTE but I only am unable to read through the app when on WiFi but can read when on LTE

Then it's certainly an issue with the website, not the source.

All images link back to their old domain, hence the source will not be updated until either the old domain redirects to the new one, or also their images are from the new domain.
![image](https://github.com/TheNetsky/extensions-generic-0.8/assets/56271887/abf656bb-924f-4df2-9862-53cc89fff047)

**Comment by jsand5048** [comment]
Netsky, Asura no longer works with any saved comics in your library. You can no longer search Asura comics either, if you find one manually from the source it’ll load but any saved won’t load

**Comment by PoloDePoli** [comment]
For those finding this bug in the future.
I was able to resolved it by using Seyden source: https://seyden.github.io/extensions-generic-0.8/mangastream/
Then in the settings for Source Settings for Asura to put the link to https://asuratoon.com [or whichever link Asura has decided to use for your country/time of day]
