### ISSUE TITLE
[BUG] AsuraScans giving the wrong redirect

### ISSUE THREAD

**Issue by smol-derp** [TheNetsky/extensions-generic-0.8#90]
**Describe the bug**
When trying to access a comic from AsuraScans I get this error back:

[PaperbackError(300)] JSError Error: The requested page https://asuratoon.com/?p=172267/ was not found! - checkResponseError@
[ERROR] [MangaViewController:loadChapters(for:):166] @:1990:32

When I go to the link it redirects me to this page: https://asuracomic.net/?p=172267/?p=172267/

**To Reproduce**
1. Go to AsuraScan tab
2. Click on any comic
3. See error

**Expected behavior**
The extension should be requesting: https://asuracomic.net/?p=172267/

**App version**
- v0.8.8-r14

**Source WITH source version**
- AsuraScans Netski | 3.0.9 from Generic Mangastream (0.8)

**Additional context**
This seems to be only happening on some networks since it works fine on my apartment wifi, but it doesn't work on cellular, university wifi, and friends wifi.

**Comment by TheNetsky** [comment]
https://github.com/TheNetsky/extensions-generic-0.8/issues/89
